### ISSUE TITLE
extra text showing up in a text field on a test

### ISSUE THREAD

**Issue by jillo** [FubuMvcArchive/storyteller#18]
This text is showing up in a text field in one of my tests: 
function(text) {        if (arguments.length == 0) {            return self.x_InnerText;        }        self.x_InnerText = text;    }

**Comment by rauhryan** [comment]
I noticed this too. I think its throwing a javascript error or somthing. Don't name the argument {text} and it will work

**Comment by jeremydmiller** [comment]
Duplicate w/ the problem about using the arg text.
