### ISSUE TITLE
newly added comments don't show up in preview mode after closing and reopening a test

### ISSUE THREAD

**Issue by jillo** [FubuMvcArchive/storyteller#29]
Steps to repro:
Open a test
Add a comment
Save the test
Close the test
Reopen the test
Result: in Peview mode, the comment you added isn't there.  When you go to Edit mode, it is there, and it remains there when you go back to Preview mode, but if you close and reopen the test again, the same thing happens

**Comment by jeremydmiller** [comment]
You know what I'm going to say and I can easily picture your face wrinkling up when you read this, but I can't reproduce the problem.  I tried it w/ both new and old tests and this never happened to me.
