### ISSUE TITLE
when entering a Comment, you have to click Close twice to get the box to close

### ISSUE THREAD

**Issue by jillo** [FubuMvcArchive/storyteller#35]

**Comment by jillo** [comment]
This only occurs for newly entered comments, not for existing comments

**Comment by jeremydmiller** [comment]
I know what you're talking about. For now, tabbing out of the comment editor makes it close.  That's a workaround, not the permanent fix

**Comment by yreynhout** [comment]
I think this is similar to the fact that when being in an input field and clicking to add a step, you have to click twice because the automatic tree view update probably causes a loss of focus.
