### ISSUE TITLE
Comment field wraps text and makes them hard to read when they intentionally have multiple lines 

### ISSUE THREAD

**Issue by jillo** [FubuMvcArchive/storyteller#37]
There are times when comments need to have multiple lines of text.  ST wraps the text when displaying the comment fields, making multiple line comments difficult to read.  The only way to see the line breaks is to click edit on the comment.

**Comment by chadmyers** [comment]
Thinking of a solution out loud:  Wrap the comments in a &lt;pre&gt; (has plusses and minuses) or use the ConvertCRLFToBreaks() method we have in dovetail.core.js to convert CR/LF in comments to <br/> tags.  I also have a corresponding reverse method ConvertBRtoCRLF().

I'm not sure those method names are exactly correct, but it's something like that.
