### ISSUE TITLE
Dead? Where is StoryTeller2 ? Nuget points here.

### ISSUE THREAD

**Issue by AnneTheAgile** [FubuMvcArchive/storyteller#75]
The Nuget gallery points to here for Storyteller2.
https://www.nuget.org/packages/Storyteller2/

Where are the docs, or are there none? 

I found this via a great post on Git workflows. Thank you!
// AnneTheAgile

**Comment by jeremydmiller** [comment]
I fixed the link.  Try https://github.com/DarthFubuMVC/storyteller2

**Comment by AnneTheAgile** [comment]
Cool, thank you @jeremydmiller ! I see it has tickets as well. 
https://github.com/DarthFubuMVC/storyteller2/issues

I will go there and ask re docs :).
