### ISSUE TITLE
Embedded grammars not getting tags applied correctly

### ISSUE THREAD

**Issue by bbehrens** [FubuMvcArchive/storyteller#9]
When creating a composite grammar, in this case Script("foo", x=> {x += this["bar"];}); the grammar name is coming through as the FormatAs value instead of the grammar key.

[Tag("hidden")]
[Hidden, FormatAs("Unique schedule key {scheduleKey}")]
public void ScheduleKey([Default("GUID")] string scheduleKey)
{
    _schedule.Key = scheduleKey;
}

public IGrammar Once()
{
    return Script("One time only", x =>
    {  
        x += this["ScheduleKey"];  
    }
}

GrammarStructure.Name for Schedule key is "Unique schedule key scheduleKey" not ScheduleKey.

**Comment by jeremydmiller** [comment]
Unnecessary
